# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TempPrep.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1287, 1064)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.pageViewerArea = QtGui.QScrollArea(self.splitter)
        self.pageViewerArea.setWidgetResizable(True)
        self.pageViewerArea.setObjectName(_fromUtf8("pageViewerArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 630, 997))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.webView = QtWebKit.QWebView(self.scrollAreaWidgetContents)
        self.webView.setGeometry(QtCore.QRect(-10, 0, 631, 991))
        self.webView.setAutoFillBackground(True)
        self.webView.setUrl(QtCore.QUrl(_fromUtf8("https://stackoverflow.com/")))
        self.webView.setObjectName(_fromUtf8("webView"))
        self.pageViewerArea.setWidget(self.scrollAreaWidgetContents)
        self.templateEditorArea = QtGui.QScrollArea(self.splitter)
        self.templateEditorArea.setWidgetResizable(True)
        self.templateEditorArea.setObjectName(_fromUtf8("templateEditorArea"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 629, 997))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 130, 591, 41))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEdit_2 = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(20, 270, 591, 41))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_4 = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.lineEdit_3 = QtGui.QLineEdit(self.horizontalLayoutWidget_4)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.horizontalLayout_5.addWidget(self.lineEdit_3)
        self.horizontalLayoutWidget_5 = QtGui.QWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(20, 310, 591, 194))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_5 = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_6.addWidget(self.label_5)
        self.textEdit_2 = QtGui.QTextEdit(self.horizontalLayoutWidget_5)
        self.textEdit_2.setObjectName(_fromUtf8("textEdit_2"))
        self.horizontalLayout_6.addWidget(self.textEdit_2)
        self.horizontalLayoutWidget_6 = QtGui.QWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(90, 520, 501, 61))
        self.horizontalLayoutWidget_6.setObjectName(_fromUtf8("horizontalLayoutWidget_6"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.checkBox = QtGui.QCheckBox(self.horizontalLayoutWidget_6)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.horizontalLayout_7.addWidget(self.checkBox)
        self.checkBox_2 = QtGui.QCheckBox(self.horizontalLayoutWidget_6)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.horizontalLayout_7.addWidget(self.checkBox_2)
        self.checkBox_3 = QtGui.QCheckBox(self.horizontalLayoutWidget_6)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.horizontalLayout_7.addWidget(self.checkBox_3)
        self.horizontalLayoutWidget_7 = QtGui.QWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(90, 590, 501, 61))
        self.horizontalLayoutWidget_7.setObjectName(_fromUtf8("horizontalLayoutWidget_7"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.pushButton = QtGui.QPushButton(self.horizontalLayoutWidget_7)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_8.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.horizontalLayoutWidget_7)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_8.addWidget(self.pushButton_2)
        self.pushButton_3 = QtGui.QPushButton(self.horizontalLayoutWidget_7)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_8.addWidget(self.pushButton_3)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 170, 591, 91))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.textEdit = QtGui.QTextEdit(self.horizontalLayoutWidget_3)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.horizontalLayout_4.addWidget(self.textEdit)
        self.horizontalLayoutWidget = QtGui.QWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 40, 591, 78))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.label_6 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_6.setGeometry(QtCore.QRect(140, 10, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.templateEditorArea.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1287, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_2.setText(_translate("MainWindow", "Description", None))
        self.label_4.setText(_translate("MainWindow", "Doc Link", None))
        self.label_5.setText(_translate("MainWindow", "Code", None))
        self.checkBox.setText(_translate("MainWindow", "To Verify", None))
        self.checkBox_2.setText(_translate("MainWindow", "Unfinished", None))
        self.checkBox_3.setText(_translate("MainWindow", "Alternative", None))
        self.pushButton.setText(_translate("MainWindow", "Accept and Next", None))
        self.pushButton_2.setText(_translate("MainWindow", "Add Alternative", None))
        self.pushButton_3.setText(_translate("MainWindow", "Quit", None))
        self.label_3.setText(_translate("MainWindow", "Comment", None))
        self.label.setText(_translate("MainWindow", "Sources", None))
        self.label_6.setText(_translate("MainWindow", "Template Preparator", None))

from PyQt4 import QtWebKit

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

